### ISSUE TITLE
Update for Version 10

### ISSUE THREAD

**Issue by Dave247** [thomasfn/EcoLawExtensionsMod#30]
As expected [beta 0.4.1](https://github.com/thomasfn/EcoLawExtensionsMod/releases/tag/0.4.1) doesn't work on version 10 of the server. The following error is thrown on startup. 

```
[23:14:09.507] [24] [Error] [Eco] Failed to start the server. Exception was Exception: ReflectionTypeLoadException
Message:Unable to load one or more of the requested types.

Source:System.Private.CoreLib

System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.

   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Eco.Shared.Utils.ReflectionCache.<>c.<GetTypesCached>b__10_0(Assembly a)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Eco.Shared.Utils.ReflectionCache.GetTypesCached(Assembly assembly)
   at Eco.Shared.Utils.ReflectionCache.<>c.<GetGameAssembliesTypes>b__21_0(Assembly assembly)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at Eco.Core.Serialization.SimpleSerializer.InitializeSerializableTypes()
   at Eco.Core.Serialization.SimpleSerializer..cctor()
System.TypeLoadException
Outer Exceptions:
One or more errors occurred. (Exception has been thrown by the target of an invocation.)
Exception has been thrown by the target of an invocation.
One or more errors occurred. (The type initializer for 'Eco.Core.Serialization.SimpleSerializer' threw an exception.)
The type initializer for 'Eco.Core.Serialization.SimpleSerializer' threw an exception.
 
[23:14:14.512] [24] [ Info] [Eco] Shutdown finished
 
[23:14:14.512] [24] [Error] [Eco] Errors report:
Failed to get derived types for 'Eco.World.Blocks.Block' in assembly 'EcoLawExtensionsMod, Version=0.4.1.0, Culture=neutral, PublicKeyToken=null' (usually safe to ignore for third party assembly). Error message: Unable to load one or more of the requested types.
: 1
Failed to start the server. Exception was Exception: ReflectionTypeLoadException
Message:Unable to load one or more of the requested types.

Source:System.Private.CoreLib

System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.

   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Eco.Shared.Utils.ReflectionCache.<>c.<GetTypesCached>b__10_0(Assembly a)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Eco.Shared.Utils.ReflectionCache.GetTypesCached(Assembly assembly)
   at Eco.Shared.Utils.ReflectionCache.<>c.<GetGameAssembliesTypes>b__21_0(Assembly assembly)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at Eco.Core.Serialization.SimpleSerializer.InitializeSerializableTypes()
   at Eco.Core.Serialization.SimpleSerializer..cctor()
System.TypeLoadException
Outer Exceptions:
One or more errors occurred. (Exception has been thrown by the target of an invocation.)
Exception has been thrown by the target of an invocation.
One or more errors occurred. (The type initializer for 'Eco.Core.Serialization.SimpleSerializer' threw an exception.)
The type initializer for 'Eco.Core.Serialization.SimpleSerializer' threw an exception.
: 1
```

**Comment by thomasfn** [comment]
Fixed in [beta 0.5.0](https://github.com/thomasfn/EcoLawExtensionsMod/releases/tag/0.5.0)
